extends:
  - recommended
rules:
  # Phase 1 gate is structural validity + required paths + version coherence.
  # We intentionally do not require security schemes or operationIds at this stage.
  security-defined: off
  info-license: off
  operation-operationId: off
  operation-4xx-response: off
  operation-2xx-response: off
