
export const elementCategories = {
    'diatomic nonmetal': { label: 'Diatomic Nonmetal', bg: 'bg-green-400' },
    'noble gas': { label: 'Noble Gas', bg: 'bg-purple-400' },
    'alkali metal': { label: 'Alkali Metal', bg: 'bg-red-400' },
    'alkaline earth metal': { label: 'Alkaline Earth Metal', bg: 'bg-orange-400' },
    'metalloid': { label: 'Metalloid', bg: 'bg-yellow-400' },
    'polyatomic nonmetal': { label: 'Polyatomic Nonmetal', bg: 'bg-emerald-400' },
    'post-transition metal': { label: 'Post-transition Metal', bg: 'bg-cyan-400' },
    'transition metal': { label: 'Transition Metal', bg: 'bg-sky-400' },
    'lanthanide': { label: 'Lanthanide', bg: 'bg-pink-400' },
    'actinide': { label: 'Actinide', bg: 'bg-rose-400' },
    'unknown': { label: 'Unknown', bg: 'bg-gray-400' }
};

export const periodicTableData = [
    { number: 1, symbol: 'H', name: 'Hydrogen', atomic_mass: 1.008, category: 'diatomic nonmetal', xpos: 1, ypos: 1 },
    { number: 2, symbol: 'He', name: 'Helium', atomic_mass: 4.0026, category: 'noble gas', xpos: 18, ypos: 1 },
    { number: 3, symbol: 'Li', name: 'Lithium', atomic_mass: 6.94, category: 'alkali metal', xpos: 1, ypos: 2 },
    { number: 4, symbol: 'Be', name: 'Beryllium', atomic_mass: 9.0122, category: 'alkaline earth metal', xpos: 2, ypos: 2 },
    { number: 5, symbol: 'B', name: 'Boron', atomic_mass: 10.81, category: 'metalloid', xpos: 13, ypos: 2 },
    { number: 6, symbol: 'C', name: 'Carbon', atomic_mass: 12.011, category: 'polyatomic nonmetal', xpos: 14, ypos: 2 },
    { number: 7, symbol: 'N', name: 'Nitrogen', atomic_mass: 14.007, category: 'diatomic nonmetal', xpos: 15, ypos: 2 },
    { number: 8, symbol: 'O', name: 'Oxygen', atomic_mass: 15.999, category: 'diatomic nonmetal', xpos: 16, ypos: 2 },
    { number: 9, symbol: 'F', name: 'Fluorine', atomic_mass: 18.998, category: 'diatomic nonmetal', xpos: 17, ypos: 2 },
    { number: 10, symbol: 'Ne', name: 'Neon', atomic_mass: 20.180, category: 'noble gas', xpos: 18, ypos: 2 },
    { number: 11, symbol: 'Na', name: 'Sodium', atomic_mass: 22.990, category: 'alkali metal', xpos: 1, ypos: 3 },
    { number: 12, symbol: 'Mg', name: 'Magnesium', atomic_mass: 24.305, category: 'alkaline earth metal', xpos: 2, ypos: 3 },
    { number: 13, symbol: 'Al', name: 'Aluminium', atomic_mass: 26.982, category: 'post-transition metal', xpos: 13, ypos: 3 },
    { number: 14, symbol: 'Si', name: 'Silicon', atomic_mass: 28.085, category: 'metalloid', xpos: 14, ypos: 3 },
    { number: 15, symbol: 'P', name: 'Phosphorus', atomic_mass: 30.974, category: 'polyatomic nonmetal', xpos: 15, ypos: 3 },
    { number: 16, symbol: 'S', name: 'Sulfur', atomic_mass: 32.06, category: 'polyatomic nonmetal', xpos: 16, ypos: 3 },
    { number: 17, symbol: 'Cl', name: 'Chlorine', atomic_mass: 35.45, category: 'diatomic nonmetal', xpos: 17, ypos: 3 },
    { number: 18, symbol: 'Ar', name: 'Argon', atomic_mass: 39.948, category: 'noble gas', xpos: 18, ypos: 3 },
    { number: 19, symbol: 'K', name: 'Potassium', atomic_mass: 39.098, category: 'alkali metal', xpos: 1, ypos: 4 },
    { number: 20, symbol: 'Ca', name: 'Calcium', atomic_mass: 40.078, category: 'alkaline earth metal', xpos: 2, ypos: 4 },
    { number: 21, symbol: 'Sc', name: 'Scandium', atomic_mass: 44.956, category: 'transition metal', xpos: 3, ypos: 4 },
    { number: 22, symbol: 'Ti', name: 'Titanium', atomic_mass: 47.867, category: 'transition metal', xpos: 4, ypos: 4 },
    { number: 23, symbol: 'V', name: 'Vanadium', atomic_mass: 50.942, category: 'transition metal', xpos: 5, ypos: 4 },
    { number: 24, symbol: 'Cr', name: 'Chromium', atomic_mass: 51.996, category: 'transition metal', xpos: 6, ypos: 4 },
    { number: 25, symbol: 'Mn', name: 'Manganese', atomic_mass: 54.938, category: 'transition metal', xpos: 7, ypos: 4 },
    { number: 26, symbol: 'Fe', name: 'Iron', atomic_mass: 55.845, category: 'transition metal', xpos: 8, ypos: 4 },
    { number: 27, symbol: 'Co', name: 'Cobalt', atomic_mass: 58.933, category: 'transition metal', xpos: 9, ypos: 4 },
    { number: 28, symbol: 'Ni', name: 'Nickel', atomic_mass: 58.693, category: 'transition metal', xpos: 10, ypos: 4 },
    { number: 29, symbol: 'Cu', name: 'Copper', atomic_mass: 63.546, category: 'transition metal', xpos: 11, ypos: 4 },
    { number: 30, symbol: 'Zn', name: 'Zinc', atomic_mass: 65.38, category: 'transition metal', xpos: 12, ypos: 4 },
    { number: 31, symbol: 'Ga', name: 'Gallium', atomic_mass: 69.723, category: 'post-transition metal', xpos: 13, ypos: 4 },
    { number: 32, symbol: 'Ge', name: 'Germanium', atomic_mass: 72.630, category: 'metalloid', xpos: 14, ypos: 4 },
    { number: 33, symbol: 'As', name: 'Arsenic', atomic_mass: 74.922, category: 'metalloid', xpos: 15, ypos: 4 },
    { number: 34, symbol: 'Se', name: 'Selenium', atomic_mass: 78.971, category: 'polyatomic nonmetal', xpos: 16, ypos: 4 },
    { number: 35, symbol: 'Br', name: 'Bromine', atomic_mass: 79.904, category: 'diatomic nonmetal', xpos: 17, ypos: 4 },
    { number: 36, symbol: 'Kr', name: 'Krypton', atomic_mass: 83.798, category: 'noble gas', xpos: 18, ypos: 4 },
    { number: 37, symbol: 'Rb', name: 'Rubidium', atomic_mass: 85.468, category: 'alkali metal', xpos: 1, ypos: 5 },
    { number: 38, symbol: 'Sr', name: 'Strontium', atomic_mass: 87.62, category: 'alkaline earth metal', xpos: 2, ypos: 5 },
    { number: 39, symbol: 'Y', name: 'Yttrium', atomic_mass: 88.906, category: 'transition metal', xpos: 3, ypos: 5 },
    { number: 40, symbol: 'Zr', name: 'Zirconium', atomic_mass: 91.224, category: 'transition metal', xpos: 4, ypos: 5 },
    { number: 41, symbol: 'Nb', name: 'Niobium', atomic_mass: 92.906, category: 'transition metal', xpos: 5, ypos: 5 },
    { number: 42, symbol: 'Mo', name: 'Molybdenum', atomic_mass: 95.96, category: 'transition metal', xpos: 6, ypos: 5 },
    { number: 43, symbol: 'Tc', name: 'Technetium', atomic_mass: 98, category: 'transition metal', xpos: 7, ypos: 5 },
    { number: 44, symbol: 'Ru', name: 'Ruthenium', atomic_mass: 101.07, category: 'transition metal', xpos: 8, ypos: 5 },
    { number: 45, symbol: 'Rh', name: 'Rhodium', atomic_mass: 102.91, category: 'transition metal', xpos: 9, ypos: 5 },
    { number: 46, symbol: 'Pd', name: 'Palladium', atomic_mass: 106.42, category: 'transition metal', xpos: 10, ypos: 5 },
    { number: 47, symbol: 'Ag', name: 'Silver', atomic_mass: 107.87, category: 'transition metal', xpos: 11, ypos: 5 },
    { number: 48, symbol: 'Cd', name: 'Cadmium', atomic_mass: 112.41, category: 'transition metal', xpos: 12, ypos: 5 },
    { number: 49, symbol: 'In', name: 'Indium', atomic_mass: 114.82, category: 'post-transition metal', xpos: 13, ypos: 5 },
    { number: 50, symbol: 'Sn', name: 'Tin', atomic_mass: 118.71, category: 'post-transition metal', xpos: 14, ypos: 5 },
    { number: 51, symbol: 'Sb', name: 'Antimony', atomic_mass: 121.76, category: 'metalloid', xpos: 15, ypos: 5 },
    { number: 52, symbol: 'Te', name: 'Tellurium', atomic_mass: 127.60, category: 'metalloid', xpos: 16, ypos: 5 },
    { number: 53, symbol: 'I', name: 'Iodine', atomic_mass: 126.90, category: 'diatomic nonmetal', xpos: 17, ypos: 5 },
    { number: 54, symbol: 'Xe', name: 'Xenon', atomic_mass: 131.29, category: 'noble gas', xpos: 18, ypos: 5 },
    { number: 55, symbol: 'Cs', name: 'Caesium', atomic_mass: 132.91, category: 'alkali metal', xpos: 1, ypos: 6 },
    { number: 56, symbol: 'Ba', name: 'Barium', atomic_mass: 137.33, category: 'alkaline earth metal', xpos: 2, ypos: 6 },
    { number: 57, symbol: 'La', name: 'Lanthanum', atomic_mass: 138.91, category: 'lanthanide', xpos: 3, ypos: 9 },
    { number: 58, symbol: 'Ce', name: 'Cerium', atomic_mass: 140.12, category: 'lanthanide', xpos: 4, ypos: 9 },
    { number: 59, symbol: 'Pr', name: 'Praseodymium', atomic_mass: 140.91, category: 'lanthanide', xpos: 5, ypos: 9 },
    { number: 60, symbol: 'Nd', name: 'Neodymium', atomic_mass: 144.24, category: 'lanthanide', xpos: 6, ypos: 9 },
    { number: 61, symbol: 'Pm', name: 'Promethium', atomic_mass: 145, category: 'lanthanide', xpos: 7, ypos: 9 },
    { number: 62, symbol: 'Sm', name: 'Samarium', atomic_mass: 150.36, category: 'lanthanide', xpos: 8, ypos: 9 },
    { number: 63, symbol: 'Eu', name: 'Europium', atomic_mass: 151.96, category: 'lanthanide', xpos: 9, ypos: 9 },
    { number: 64, symbol: 'Gd', name: 'Gadolinium', atomic_mass: 157.25, category: 'lanthanide', xpos: 10, ypos: 9 },
    { number: 65, symbol: 'Tb', name: 'Terbium', atomic_mass: 158.93, category: 'lanthanide', xpos: 11, ypos: 9 },
    { number: 66, symbol: 'Dy', name: 'Dysprosium', atomic_mass: 162.50, category: 'lanthanide', xpos: 12, ypos: 9 },
    { number: 67, symbol: 'Ho', name: 'Holmium', atomic_mass: 164.93, category: 'lanthanide', xpos: 13, ypos: 9 },
    { number: 68, symbol: 'Er', name: 'Erbium', atomic_mass: 167.26, category: 'lanthanide', xpos: 14, ypos: 9 },
    { number: 69, symbol: 'Tm', name: 'Thulium', atomic_mass: 168.93, category: 'lanthanide', xpos: 15, ypos: 9 },
    { number: 70, symbol: 'Yb', name: 'Ytterbium', atomic_mass: 173.05, category: 'lanthanide', xpos: 16, ypos: 9 },
    { number: 71, symbol: 'Lu', name: 'Lutetium', atomic_mass: 174.97, category: 'lanthanide', xpos: 17, ypos: 9 },
    { number: 72, symbol: 'Hf', name: 'Hafnium', atomic_mass: 178.49, category: 'transition metal', xpos: 4, ypos: 6 },
    { number: 73, symbol: 'Ta', name: 'Tantalum', atomic_mass: 180.95, category: 'transition metal', xpos: 5, ypos: 6 },
    { number: 74, symbol: 'W', name: 'Tungsten', atomic_mass: 183.84, category: 'transition metal', xpos: 6, ypos: 6 },
    { number: 75, symbol: 'Re', name: 'Rhenium', atomic_mass: 186.21, category: 'transition metal', xpos: 7, ypos: 6 },
    { number: 76, symbol: 'Os', name: 'Osmium', atomic_mass: 190.23, category: 'transition metal', xpos: 8, ypos: 6 },
    { number: 77, symbol: 'Ir', name: 'Iridium', atomic_mass: 192.22, category: 'transition metal', xpos: 9, ypos: 6 },
    { number: 78, symbol: 'Pt', name: 'Platinum', atomic_mass: 195.08, category: 'transition metal', xpos: 10, ypos: 6 },
    { number: 79, symbol: 'Au', name: 'Gold', atomic_mass: 196.97, category: 'transition metal', xpos: 11, ypos: 6 },
    { number: 80, symbol: 'Hg', name: 'Mercury', atomic_mass: 200.59, category: 'transition metal', xpos: 12, ypos: 6 },
    { number: 81, symbol: 'Tl', name: 'Thallium', atomic_mass: 204.38, category: 'post-transition metal', xpos: 13, ypos: 6 },
    { number: 82, symbol: 'Pb', name: 'Lead', atomic_mass: 207.2, category: 'post-transition metal', xpos: 14, ypos: 6 },
    { number: 83, symbol: 'Bi', name: 'Bismuth', atomic_mass: 208.98, category: 'post-transition metal', xpos: 15, ypos: 6 },
    { number: 84, symbol: 'Po', name: 'Polonium', atomic_mass: 209, category: 'post-transition metal', xpos: 16, ypos: 6 },
    { number: 85, symbol: 'At', name: 'Astatine', atomic_mass: 210, category: 'metalloid', xpos: 17, ypos: 6 },
    { number: 86, symbol: 'Rn', name: 'Radon', atomic_mass: 222, category: 'noble gas', xpos: 18, ypos: 6 },
    { number: 87, symbol: 'Fr', name: 'Francium', atomic_mass: 223, category: 'alkali metal', xpos: 1, ypos: 7 },
    { number: 88, symbol: 'Ra', name: 'Radium', atomic_mass: 226, category: 'alkaline earth metal', xpos: 2, ypos: 7 },
    { number: 89, symbol: 'Ac', name: 'Actinium', atomic_mass: 227, category: 'actinide', xpos: 3, ypos: 10 },
    { number: 90, symbol: 'Th', name: 'Thorium', atomic_mass: 232.04, category: 'actinide', xpos: 4, ypos: 10 },
    { number: 91, symbol: 'Pa', name: 'Protactinium', atomic_mass: 231.04, category: 'actinide', xpos: 5, ypos: 10 },
    { number: 92, symbol: 'U', name: 'Uranium', atomic_mass: 238.03, category: 'actinide', xpos: 6, ypos: 10 },
    { number: 93, symbol: 'Np', name: 'Neptunium', atomic_mass: 237, category: 'actinide', xpos: 7, ypos: 10 },
    { number: 94, symbol: 'Pu', name: 'Plutonium', atomic_mass: 244, category: 'actinide', xpos: 8, ypos: 10 },
    { number: 95, symbol: 'Am', name: 'Americium', atomic_mass: 243, category: 'actinide', xpos: 9, ypos: 10 },
    { number: 96, symbol: 'Cm', name: 'Curium', atomic_mass: 247, category: 'actinide', xpos: 10, ypos: 10 },
    { number: 97, symbol: 'Bk', name: 'Berkelium', atomic_mass: 247, category: 'actinide', xpos: 11, ypos: 10 },
    { number: 98, symbol: 'Cf', name: 'Californium', atomic_mass: 251, category: 'actinide', xpos: 12, ypos: 10 },
    { number: 99, symbol: 'Es', name: 'Einsteinium', atomic_mass: 252, category: 'actinide', xpos: 13, ypos: 10 },
    { number: 100, symbol: 'Fm', name: 'Fermium', atomic_mass: 257, category: 'actinide', xpos: 14, ypos: 10 },
    { number: 101, symbol: 'Md', name: 'Mendelevium', atomic_mass: 258, category: 'actinide', xpos: 15, ypos: 10 },
    { number: 102, symbol: 'No', name: 'Nobelium', atomic_mass: 259, category: 'actinide', xpos: 16, ypos: 10 },
    { number: 103, symbol: 'Lr', name: 'Lawrencium', atomic_mass: 262, category: 'actinide', xpos: 17, ypos: 10 },
    { number: 104, symbol: 'Rf', name: 'Rutherfordium', atomic_mass: 267, category: 'transition metal', xpos: 4, ypos: 7 },
    { number: 105, symbol: 'Db', name: 'Dubnium', atomic_mass: 270, category: 'transition metal', xpos: 5, ypos: 7 },
    { number: 106, symbol: 'Sg', name: 'Seaborgium', atomic_mass: 271, category: 'transition metal', xpos: 6, ypos: 7 },
    { number: 107, symbol: 'Bh', name: 'Bohrium', atomic_mass: 270, category: 'transition metal', xpos: 7, ypos: 7 },
    { number: 108, symbol: 'Hs', name: 'Hassium', atomic_mass: 277, category: 'transition metal', xpos: 8, ypos: 7 },
    { number: 109, symbol: 'Mt', name: 'Meitnerium', atomic_mass: 276, category: 'unknown', xpos: 9, ypos: 7 },
    { number: 110, symbol: 'Ds', name: 'Darmstadtium', atomic_mass: 281, category: 'unknown', xpos: 10, ypos: 7 },
    { number: 111, symbol: 'Rg', name: 'Roentgenium', atomic_mass: 280, category: 'unknown', xpos: 11, ypos: 7 },
    { number: 112, symbol: 'Cn', name: 'Copernicium', atomic_mass: 285, category: 'transition metal', xpos: 12, ypos: 7 },
    { number: 113, symbol: 'Nh', name: 'Nihonium', atomic_mass: 286, category: 'unknown', xpos: 13, ypos: 7 },
    { number: 114, symbol: 'Fl', name: 'Flerovium', atomic_mass: 289, category: 'post-transition metal', xpos: 14, ypos: 7 },
    { number: 115, symbol: 'Mc', name: 'Moscovium', atomic_mass: 288, category: 'unknown', xpos: 15, ypos: 7 },
    { number: 116, symbol: 'Lv', name: 'Livermorium', atomic_mass: 293, category: 'unknown', xpos: 16, ypos: 7 },
    { number: 117, symbol: 'Ts', name: 'Tennessine', atomic_mass: 294, category: 'unknown', xpos: 17, ypos: 7 },
    { number: 118, symbol: 'Og', name: 'Oganesson', atomic_mass: 294, category: 'unknown', xpos: 18, ypos: 7 }
]
