"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateReport = generateReport;
const admin = __importStar(require("firebase-admin"));
/**
 * LARI-Reasoning: Multi-step workflows and report generation
 */
async function generateReport(inspectionId) {
    // Fetch inspection data
    const inspectionDoc = await admin
        .firestore()
        .collection('inspections')
        .doc(inspectionId)
        .get();
    if (!inspectionDoc.exists) {
        throw new Error('Inspection not found');
    }
    const inspection = inspectionDoc.data();
    // Fetch findings
    const findingsSnapshot = await admin
        .firestore()
        .collection('inspections')
        .doc(inspectionId)
        .collection('findings')
        .get();
    const findings = findingsSnapshot.docs.map((doc) => doc.data());
    // Generate report (simple text for demo)
    const reportText = `
# Inspection Report

**Inspection ID**: ${inspectionId}
**Type**: ${inspection?.type}
**Property**: ${inspection?.property}
**Date**: ${new Date().toLocaleDateString()}

## Findings

${findings.map((f, i) => `
### Finding ${i + 1}
- **Description**: ${f.description}
- **Code Reference**: ${f.code_reference}
- **Severity**: ${f.severity}
`).join('\n')}

## Summary

Total findings: ${findings.length}

---
*Generated by ScingOS | Built with Bona Fide Intelligence*
  `.trim();
    // TODO: Convert to PDF, store in Cloud Storage
    return reportText;
}
//# sourceMappingURL=reasoning.js.map