import * as fs from "fs/promises";
import * as path from "path";

function toPascalCase(slug: string) {
  return slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

export function slugifyEngineId(description: string): string {
  const d = description.toLowerCase();
  // Phase 1: special-case the investor demo phrase.
  if (d.includes("anomaly") && d.includes("correlation")) return "anomaly-correlation";

  const words = d
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter(Boolean);

  const trimmed = words.slice(0, 4).join("-");
  return trimmed || `engine-${Date.now()}`;
}

export async function scaffoldEngine(repoRoot: string, description: string) {
  const id = slugifyEngineId(description);
  const fileBase = toPascalCase(id);

  const enginesDir = path.join(repoRoot, "scing", "engines");
  const filePath = path.join(enginesDir, `${fileBase}.ts`);

  await fs.mkdir(enginesDir, { recursive: true });

  try {
    await fs.access(filePath);
    return { id, filePath, created: false };
  } catch {
    // continue
  }

  const contents = `export type ${fileBase}Input = {\n  signal: string;\n};\n\nexport type ${fileBase}Output = {\n  anomaly: boolean;\n  confidence: number;\n  notes: string[];\n};\n\n// Phase 1 stub engine generated by BFI governed execution.\nexport function ${fileBase}(input: ${fileBase}Input): ${fileBase}Output {\n  const signal = (input.signal || \"\").trim();\n  const anomaly = signal.length > 0 && /error|fail|anomaly|spike/i.test(signal);\n  return {\n    anomaly,\n    confidence: anomaly ? 0.6 : 0.4,\n    notes: [\"Stub engine. Replace with real correlator.\"],\n  };\n}\n`;

  await fs.writeFile(filePath, contents, "utf8");
  return { id, filePath, created: true };
}
