"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lariSealBlock = lariSealBlock;
const runReadiness_1 = require("../../lari/readiness/runReadiness");
function lariSealBlock(checkedAtIso) {
    const r = (0, runReadiness_1.runReadiness)(checkedAtIso);
    if (!r.ready)
        return null;
    return {
        section: 'lari_seal',
        title: 'LARI Field-Readiness Seal',
        content: {
            statement: 'This report was generated by a field-ready LARI engine suite with evidence-linked, audited outputs.',
            checkedAt: r.checkedAt,
            capabilityMatrix: r.matrix,
        },
    };
}
//# sourceMappingURL=lariSeal.js.map