import { runReadiness } from '../../lari/readiness/runReadiness';

export function lariSealBlock(checkedAtIso?: string) {
  const r = runReadiness(checkedAtIso);
  if (!r.ready) return null;

  return {
    section: 'lari_seal',
    title: 'LARI Field-Readiness Seal',
    content: {
      statement:
        'This report was generated by a field-ready LARI engine suite with evidence-linked, audited outputs.',
      checkedAt: r.checkedAt,
      capabilityMatrix: r.matrix,
    },
  };
}
