@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM ============================================================
REM  SCINGULAR / SCING — SRT SCAFFOLD (Consolidated + VSCI Safe)
REM  FIXES: PowerShell quoting issues by using CERTUTIL base64 decode
REM  Usage: Save as tools\VSCI_CB_SRT_Scaffold.bat then run it from repo root.
REM ============================================================

echo.
echo [SCING] SRT scaffold (Consolidated Batch) starting...
echo.

REM --- Ensure tools folder exists ---
if not exist "tools" mkdir "tools"

REM --- Write base64 payload to tools\scaffold-srt.b64 ---
echo [SCING] Writing payload...
> "tools\scaffold-srt.b64" (
  echo aW1wb3J0IGZzIGZyb20gIm5vZGU6ZnMiOwppbXBvcnQgcGF0aCBmcm9tICJub2RlOnBhdGgiOwoKY29uc3Qgcm9vdCA9IHByb2Nlc3MuY3dkKCk7Cgpjb25zdCBmaWxlcyA9IHsKICAic2NpbmcvY29yZS9zY2luZ1J1bnRpbWUudHMiOiBg
  echo aW1wb3J0IHsgU1JUUnVudGltZSB9IGZyb20gJy4uL3NydC9zcnRSdW50aW1lJwppbXBvcnQgeyBvcmRlckFuZEZvY3VzIH0gZnJvbSAnLi9vcmRlckZvY3VzUHJvdG9jb2wnCmltcG9ydCB7IGFsbG93R3Jvd3RoIH0gZnJvbSAnLi9ncm93dGhQcm90b2NvbCcKaW1wb3J0IHsgYWxsb3dDYXRhbHlzdCB9IGZyb20gJy4vY2F0YWx5c3RQcm90b2NvbCcKaW1wb3J0IHsgQXVkaXRMb2cgfSBmcm9tICcuLi9ndWFyZHMvYXVkaXRMb2cnCgpleHBvcnQgdHlwZSBTZW5zb3JGbHV4ID0gbnVtYmVyW10KCi8qKgogKiBTY2luZ1J1bnRpbWU6IGhvc3QgcnVudGltZSB0aGF0IGNvbnRpbnVvdXNseSAqaW52b2tlcyBleGlzdGVuY2UqLgogKiBJTVBPUlRBTlQ6IFRoaXMgcnVudGltZSBtdXN0IG5vdCBvd24gZGV0ZXJtaW5pc3RpYyBwbGF5YmFjayBvciBhbmltYXRpb24gbG9vcHMuCiAqLwpleHBvcnQgY2xhc3MgU2NpbmdSdW50aW1lIHsKICBwcml2YXRlIHNydCA9IG5ldyBTUlRSdW50aW1lKCkKICBwcml2YXRlIGF1ZGl0ID0gbmV3IEF1ZGl0TG9nKCkKCiAgZXhpc3Qoc2Vuc29yRmx1eDogU2Vuc29yRmx1eCwgb3B0cz86IHsgcGVyc2lzdGVuY2U/OiBudW1iZXI7IHN0cmFpbj86IG51bWJlciB9KSB7CiAgICB0aGlzLnNydC5leGlzdChzZW5zb3JGbHV4KQoKICAgIGNvbnN0IGluZmx1ZW5jZSA9IHRoaXMuc3J0LmluZmx1ZW5jZS5zYW1wbGUoKQogICAgY29uc3Qgb3JkZXJlZCA9IG9yZGVyQW5kRm9jdXMoaW5mbHVlbmNlKQoKICAgIC8vIEZvcm1hbCBlbmdpbmVlcmluZyBnYXRlOiBvbmx5IGVuZ2luZWVyIHdoZW4gb3JkZXJlZCA9PT0gdHJ1ZQogICAgdGhpcy5hdWRpdC5ub3RlKCdvcmRlckZvY3VzJywgeyBvcmRlcmVkIH0pCgogICAgY29uc3QgcGVyc2lzdGVuY2UgPSBvcHRzPy5wZXJzaXN0ZW5jZSA/PyAwCiAgICBjb25zdCBzdHJhaW4gPSBvcHRzPy5zdHJhaW4gPz8gMAoKICAgIGNvbnN0IGdyb3d0aE9rID0gYWxsb3dHcm93dGgob3JkZXJlZCwgcGVyc2lzdGVuY2UpCiAgICBjb25zdCBjYXRhbHlzdE9rID0gYWxsb3dDYXRhbHlzdChvcmRlcmVkLCBzdHJhaW4pCgogICAgdGhpcy5hdWRpdC5ub3RlKCdncm93dGhFbGlnaWJpbGl0eScsIHsgZ3Jvd3RoT2ssIHBlcnNpc3RlbmNlIH0pCiAgICB0aGlzLmF1ZGl0Lm5vdGUoJ2NhdGFseXN0RWxpZ2liaWxpdHknLCB7IGNhdGFseXN0T2ssIHN0cmFpbiB9KQogIH0KfQpgLAogICJzY2luZy9jb3JlL29yZGVyRm9jdXNQcm90b2NvbC50cyI6IGAvKioKICogT3JkZXIgJiBGb2N1cyBQcm90b2NvbAogKiBTY2luZyBlbmdpbmVlcnMgc29sdXRpb25zIG9ubHkgd2hlbiBvcmRlci9mb2N1cyBuYXR1cmFsbHkgZW1lcmdlLgogKi8KZXhwb3J0IGZ1bmN0aW9uIG9yZGVyQW5kRm9jdXMoaW5mbHVlbmNlOiBudW1iZXJbXSk6IGJvb2xlYW4gewogIGlmICghaW5mbHVlbmNlPy5sZW5ndGgpIHJldHVybiBmYWxzZQogIGNvbnN0IG1lYW5BYnMgPSBpbmZsdWVuY2UucmVkdWNlKChhLCBiKSA9PiBhICsgTWF0aC5hYnMoYiksIDApIC8gaW5mbHVlbmNlLmxlbmd0aAogIHJldHVybiBtZWFuQWJzIDwgMC43NQp9CmAsCiAgInNjaW5nL2NvcmUvZ3Jvd3RoUHJvdG9jb2wudHMiOiBgLyoqCiAqIEdyb3d0aCBQcm90b2NvbCAoc2VsZi1kcml2ZW4gc3ViLWVuZ2luZSBnZW5lc2lzIGVsaWdpYmlsaXR5KS4KICogQXV0b25vbW91czsgbm8gdXNlciBjb25maXJtYXRpb24gcmVxdWlyZWQuCiAqLwpleHBvcnQgZnVuY3Rpb24gYWxsb3dHcm93dGgob3JkZXJlZDogYm9vbGVhbiwgcGVyc2lzdGVuY2U6IG51bWJlcik6IGJvb2xlYW4gewogIHJldHVybiBvcmRlcmVkICYmIHBlcnNpc3RlbmNlID4gMC44Cn0KYCwKICAic2NpbmcvY29yZS9jYXRhbHlzdFByb3RvY29sLnRzIjogYC8qKgogKiBDYXRhbHlzdCBQcm90b2NvbCAoZXh0ZXJuYWxseS1pbmR1Y2VkIHN1Yi1lbmdpbmUgZ2VuZXNpcyBlbGlnaWJpbGl0eSkuCiAqIEF1dG9ub21vdXM7IG5vIHVzZXIgY29uZmlybWF0aW9uIHJlcXVpcmVkLgogKi8KZXhwb3J0IGZ1bmN0aW9uIGFsbG93Q2F0YWx5c3Qob3JkZXJlZDogYm9vbGVhbiwgc3RyYWluOiBudW1iZXIpOiBib29sZWFuIHsKICByZXR1cm4gb3JkZXJlZCAmJiBzdHJhaW4gPiAwLjkKfQpgLAogICJzY2luZy9jb3JlL2VuZ2luZVJlZ2lzdHJ5LnRzIjogYGV4cG9ydCB0eXBlIEVuZ2luZUZhbWlseSA9CiAgfCAnb3JjaGVzdHJhdG9yJwogIHwgJ2NvZ25pdGlvbicKICB8ICdleHByZXNzaW9uJwogIHwgJ3N1YmVuZ2luZScKCmV4cG9ydCB0eXBlIEVuZ2luZVJlY29yZCA9IHsKICBpZDogc3RyaW5nCiAgZmFtaWx5OiBFbmdpbmVGYW1pbHkKICBkZXNjcmlwdGlvbjogc3RyaW5nCiAgZW5hYmxlZDogYm9vbGVhbgp9CgpleHBvcnQgY29uc3QgZW5naW5lUmVnaXN0cnk6IEVuZ2luZVJlY29yZFtdID0gWwogIHsKICAgIGlkOiAnc3J0LWNvcmUnLAogICAgZmFtaWx5OiAnZXhwcmVzc2lvbicsCiAgICBkZXNjcmlwdGlvbjogJ1NSVCBmZWRlcmF0aW9uICsgaW5mbHVlbmNlIGZpZWxkICsgbW90aWYgY29uc3RyYWludHMnLAogICAgZW5hYmxlZDogdHJ1ZSwKICB9LApdCmAsCiAgInNjaW5nL3NydC9pbmZsdWVuY2VGaWVsZC50cyI6IGAvKioKICogSW5mbHVlbmNlRmllbGQ6IHNoYXJlZCBjb250aW51b3VzIHNpZ25hbCBzdWJzdHJhdGUuCiAqIE5vIHJlc2V0cy4gTm8gcmVwbGF5IGNhY2hlcy4gTm8gZGV0ZXJtaW5pc3RpYyBzdGFiaWxpemF0aW9uLgogKi8KZXhwb3J0IGNsYXNzIEluZmx1ZW5jZUZpZWxkIHsKICBwcml2YXRlIGZpZWxkOiBudW1iZXJbXQoKICBjb25zdHJ1Y3RvcihkaW06IG51bWJlciA9IDE2KSB7CiAgICB0aGlzLmZpZWxkID0gbmV3IEFycmF5KGRpbSkuZmlsbCgwKQogIH0KCiAgaW5nZXN0KGZsdXg6IG51bWJlcltdKSB7CiAgICBjb25zdCBuID0gTWF0aC5taW4odGhpcy5maWVsZC5sZW5ndGgsIGZsdXgubGVuZ3RoKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBuOyBpKyspIHsKICAgICAgY29uc3QgZXBzID0gKE1hdGgucmFuZG9tKCkgLSAwLjUpICogMC4wMDAxCiAgICAgIHRoaXMuZmllbGRbaV0gPSB0aGlzLmZpZWxkW2ldICsgZmx1eFtpXSArIGVwcwogICAgfQogICAgZm9yIChsZXQgaSA9IG47IGkgPCB0aGlzLmZpZWxkLmxlbmd0aDsgaSsrKSB7CiAgICAgIHRoaXMuZmllbGRbaV0gPSB0aGlzLmZpZWxkW2ldICogKDAuOTk5ICsgTWF0aC5yYW5kb20oKSAqIDAuMDAyKQogICAgfQogIH0KCiAgc2FtcGxlKCk6IG51bWJlcltdIHsKICAgIHJldHVybiB0aGlzLmZpZWxkLnNsaWNlKCkKICB9Cn0K

REM NOTE:
REM The base64 above is intentionally compacted. If your editor wraps lines,
REM that's OK—CERTUTIL can still decode as long as content stays base64.

REM --- Decode to tools\scaffold-srt.mjs ---
echo [SCING] Decoding payload to tools\scaffold-srt.mjs ...
certutil -f -decode "tools\scaffold-srt.b64" "tools\scaffold-srt.mjs" >nul
if errorlevel 1 (
  echo [ERROR] certutil decode failed. Ensure certutil is available (Windows) and try again.
  exit /b 1
)

REM --- Run Node scaffold generator ---
echo [SCING] Running Node scaffold generator...
where node >nul 2>nul
if errorlevel 1 (
  echo [ERROR] Node.js not found in PATH. Install Node 18+ then re-run this batch.
  exit /b 1
)

node "tools\scaffold-srt.mjs"
if errorlevel 1 (
  echo [ERROR] Node scaffold failed. Check output above.
  exit /b 1
)

echo.
echo ✅ [SCING] Complete. SRT scaffold created under .\scing\
echo.
exit /b 0